### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by sansculotte** [pd-externals/flite#1]
make fails with:
flite.c:27:25: fatal error: flite/flite.h: No such file or directory

and indeed, the whole flite directory seems to be missing from the repository.

also the README installation section says to run ./configure which is also missing.

**Comment by umlaeute** [comment]
it's not missing.
it's an *external* dependency, which you have to install manually.

**Comment by sansculotte** [comment]
sorry for the false alarm.

> it's an external dependency, which you have to install manually.

i that found out too, so i closed the issue. however, i still have trouble building the external. let me highlight the respective section from the README:

> First, build and install the libflite distribution.
check. i got the lib installed:

```
$ ls /usr/local/lib/libflite*
/usr/local/lib/libflite.a
/usr/local/lib/libflite_cmu_indic_lang.a
/usr/local/lib/libflite_cmu_time_awb.a
/usr/local/lib/libflite_cmu_us_kal.a
/usr/local/lib/libflite_usenglish.a
/usr/local/lib/libflite_cmu_grapheme_lang.a
/usr/local/lib/libflite_cmu_indic_lex.a
/usr/local/lib/libflite_cmu_us_awb.a
/usr/local/lib/libflite_cmu_us_rms.a
/usr/local/lib/libflite_cmu_grapheme_lex.a
/usr/local/lib/libflite_cmulex.a
/usr/local/lib/libflite_cmu_us_kal16.a
/usr/local/lib/libflite_cmu_us_slt.a
```

> Then, issue the following commands to the shell:

>     cd PACKAGENAME-X.YY  (or wherever you extracted this distribution)
that's the external now, right?

>     ./configure
there's no configure in the repository, neither a configure.ac for automake. but a makefile is there, soo...

>     make
>     make install

is failing with:

```
++++ info: using Makefile.pdlibbuilder version 0.4.4
++++ info: using Pd API /usr/include/pd/m_pd.h
++++ info: making target all in lib flite
++++ info: evaluating implicit prerequisites in lib flite.....
++++ info: linking objects in flite.pd_linux for lib flite
cc -rdynamic -shared -fPIC -Wl,-rpath,"\$ORIGIN",--enable-new-dtags    -o flite.pd_linux flite.o  -lc -lm -lflite_cmu_us_kal16 -lflite_cmulex -lflite -lm  
/usr/bin/ld: //usr/local/lib/libflite_cmu_us_kal16.a(cmu_us_kal16.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libflite_cmu_us_kal16.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
pd-lib-builder//Makefile.pdlibbuilder:792: recipe for target 'flite.pd_linux' failed
make: *** [flite.pd_linux] Error 1
```
thanks for helping me out there.

**Comment by umlaeute** [comment]
that seems to be an issue of the build system of libflite: on amd64 you *must* compile the (entire) libray with `-fPIC`. on other archs this is usually a good thing too.

also, I don't know your distribution, but have you tried `apt install pd-flite`?
