### ISSUE TITLE
missing ld flag

### ISSUE THREAD

**Issue by patricecolet** [pd-externals/flite#3]
On arm64 running fine with https://github.com/festvox/flite after adding  -lflite_usenglish to ld flags.

**Comment by umlaeute** [comment]
hmm, the flag is not missing here on *amd64* and *arm64*.


```
$ make
++++ info: using Makefile.pdlibbuilder version 0.4.4
++++ info: using Pd API /usr/include/pd/m_pd.h
++++ info: making target all in lib flite
++++ info: making flite.o in lib flite
cc -DPD -I "/usr/include/pd" -DUNIX  -fPIC -DVERSION='"0.02-3"' -DVOICE=kal16 -Wall -Wextra -Wshadow -Winline -Wstrict-aliasing -O3 -ffast-math -funroll-loops -fomit-frame-pointer  -o flite.o -c flite.c
flite.c: In function 'flite_setup':
flite.c:259:27: warning: cast between incompatible function types from 'void * (*)(t_symbol *)' {aka 'void * (*)(struct _symbol *)'} to 'void * (*)(void)' [-Wcast-function-type]
  259 |                           (t_newmethod)flite_new,  // newmethod
      |                           ^
++++ info: linking objects in flite.pd_linux for lib flite
cc -rdynamic -shared -fPIC -Wl,-rpath,"\$ORIGIN",--enable-new-dtags    -o flite.pd_linux flite.o  -lc -lm -lflite_cmu_us_kal16 -lflite_cmulex -lflite -lm  
++++info: target all in lib flite completed
$ ldd flite.pd_linux 
        linux-vdso.so.1 (0x0000ffff8e652000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8e440000)
        libflite_cmu_us_kal16.so.1 => /usr/lib/aarch64-linux-gnu/libflite_cmu_us_kal16.so.1 (0x0000ffff8e040000)
        libflite.so.1 => /usr/lib/aarch64-linux-gnu/libflite.so.1 (0x0000ffff8dfe0000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff8e615000)
        libflite_usenglish.so.1 => /usr/lib/aarch64-linux-gnu/libflite_usenglish.so.1 (0x0000ffff8dfa0000)
        libflite_cmulex.so.1 => /usr/lib/aarch64-linux-gnu/libflite_cmulex.so.1 (0x0000ffff8dee0000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff8de30000)
        libasound.so.2 => /usr/lib/aarch64-linux-gnu/libasound.so.2 (0x0000ffff8dd00000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffff8dcd0000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff8dca0000)
$ pd -nrt -nogui flite-help.pd 
flite: Text-to-Speech external v0.02-3 by Bryan Jurish
```

so what is missing and why does it not work for you?

**Comment by umlaeute** [comment]
forgot to add: my tests where with flite 2.2 (actually flite 2.2-5, as packaged in Debian)

**Comment by patricecolet** [comment]
Forgot to mention the OS is Darwin...

d-flite % make        
++++ info: using Makefile.pdlibbuilder version 0.4.4
++++ info: using Pd API /Applications/Pd-0.52-2.app/Contents/Resources/src/m_pd.h
++++ info: making target all in lib flite
++++ info: making flite.o in lib flite
cc -DPD -I "/Applications/Pd-0.52-2.app/Contents/Resources/src" -DUNIX -DMACOSX -I /sw/include   -DVERSION='"0.02-3"' -DVOICE=kal16 -Wall -Wextra -Wshadow -Winline -Wstrict-aliasing -O3 -ffast-math -funroll-loops -fomit-frame-pointer   -o flite.o -c flite.c
++++ info: linking objects in flite.pd_darwin for lib flite
cc -undefined suppress -flat_namespace -bundle     -o flite.pd_darwin flite.o  -lc -lflite_cmu_us_kal16 -lflite_cmulex -lflite -lm  
++++info: target all in lib flite completed

/Users/patricecolet/repo/pd-flite/flite.pd_darwin: dlopen(/Users/patricecolet/repo/pd-flite/flite.pd_darwin, 0x000A): symbol not found in flat namespace (_usenglish_init)

flite: Text-to-Speech external v0.02-3 by Bryan Jurish

**Comment by umlaeute** [comment]
that should be fixed in current `main`
